// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZeeDhFJagW80LQieoG6z-l1HT_ZP2Zk',
    appId: '1:501011440652:web:23f6e564e93d3283a83a29',
    messagingSenderId: '501011440652',
    projectId: 'talhaclothhouse',
    authDomain: 'talhaclothhouse.firebaseapp.com',
    storageBucket: 'talhaclothhouse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWYylDchayT1H5NRL80weanlPLRhxBrlk',
    appId: '1:501011440652:android:19ce289bd9b6424fa83a29',
    messagingSenderId: '501011440652',
    projectId: 'talhaclothhouse',
    storageBucket: 'talhaclothhouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbgVIfONVkqz4KqgrV6HRRXHO_NrQMVw',
    appId: '1:501011440652:ios:611da3d016636563a83a29',
    messagingSenderId: '501011440652',
    projectId: 'talhaclothhouse',
    storageBucket: 'talhaclothhouse.firebasestorage.app',
    iosBundleId: 'net.ammarafzal.talhaclothhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbgVIfONVkqz4KqgrV6HRRXHO_NrQMVw',
    appId: '1:501011440652:ios:611da3d016636563a83a29',
    messagingSenderId: '501011440652',
    projectId: 'talhaclothhouse',
    storageBucket: 'talhaclothhouse.firebasestorage.app',
    iosBundleId: 'net.ammarafzal.talhaclothhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZeeDhFJagW80LQieoG6z-l1HT_ZP2Zk',
    appId: '1:501011440652:web:b3d16131a4345640a83a29',
    messagingSenderId: '501011440652',
    projectId: 'talhaclothhouse',
    authDomain: 'talhaclothhouse.firebaseapp.com',
    storageBucket: 'talhaclothhouse.firebasestorage.app',
  );

}